[package]
name = "jq721"
edition = "2024.beta" 
license = "MIT"         
authors = ["Hercules (sirhercules27@yahoo.com)"]     

[dependencies]
Kiosk = { git = "https://github.com/MystenLabs/apps.git", subdir = "kiosk", rev = "main" }
joystiq = { git = "https://github.com/joystiqio/joystiq-nft-core.git", rev = "main" }

[addresses]
jq721 = "0x0"

[dev-dependencies]

[dev-addresses]
